# Generated by Django 4.0.2 on 2022-08-16 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='word',
            new_name='words',
        ),
    ]
